CREATE TABLE CLIENTES (
    CODCLIENTE NUMBER PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(150) NOT NULL,
    CIDADE VARCHAR2(100) NOT NULL,
    DATA_CADASTRO DATE NOT NULL
);

CREATE TABLE FILMES (
    CODFILME NUMBER PRIMARY KEY,
    TITULO VARCHAR2(150) NOT NULL,
    GENERO VARCHAR2(50) NOT NULL,
    ANO_LANCAMENTO NUMBER NOT NULL,
    VALOR NUMBER(10,2) NOT NULL
);

CREATE TABLE LOCACOES (
    CODLOCACAO NUMBER PRIMARY KEY,
    CODCLIENTE NUMBER NOT NULL,
    CODFILME NUMBER NOT NULL,
    DATA_LOCACAO DATE NOT NULL,
    VALOR_PAGO NUMBER(10,2) NOT NULL
);

ALTER TABLE LOCACOES
ADD CONSTRAINT FK_LOCACAO_CLIENTE
FOREIGN KEY (CODCLIENTE)
REFERENCES CLIENTES (CODCLIENTE);

ALTER TABLE LOCACOES
ADD CONSTRAINT FK_LOCACAO_FILME
FOREIGN KEY (CODFILME)
REFERENCES FILMES (CODFILME);
