INSERT INTO CLIENTES (CODCLIENTE, NOME, EMAIL, CIDADE, DATA_CADASTRO)
VALUES (1, 'Carlos Silva', 'carlos@email.com', 'São Paulo', DATE '2026-01-15');

INSERT INTO CLIENTES (CODCLIENTE, NOME, EMAIL, CIDADE, DATA_CADASTRO)
VALUES (2, 'Mariana Souza', 'mariana@email.com', 'Campinas', DATE '2026-02-10');

INSERT INTO CLIENTES (CODCLIENTE, NOME, EMAIL, CIDADE, DATA_CADASTRO)
VALUES (3, 'Rafael Oliveira', 'rafael@email.com', 'Santos', DATE '2026-03-05');

INSERT INTO CLIENTES (CODCLIENTE, NOME, EMAIL, CIDADE, DATA_CADASTRO)
VALUES (4, 'Juliana Santos', 'juliana@email.com', 'São Paulo', DATE '2026-03-20');

INSERT INTO CLIENTES (CODCLIENTE, NOME, EMAIL, CIDADE, DATA_CADASTRO)
VALUES (5, 'Pedro Almeida', 'pedro@email.com', 'Jundiaí', DATE '2026-04-02');

INSERT INTO FILMES (CODFILME, TITULO, GENERO, ANO_LANCAMENTO, VALOR)
VALUES (1, 'Interestelar', 'Ficção Científica', 2014, 29.90);

INSERT INTO FILMES (CODFILME, TITULO, GENERO, ANO_LANCAMENTO, VALOR)
VALUES (2, 'O Poderoso Chefão', 'Drama', 1972, 39.90);

INSERT INTO FILMES (CODFILME, TITULO, GENERO, ANO_LANCAMENTO, VALOR)
VALUES (3, 'Matrix', 'Ficção Científica', 1999, 34.90);

INSERT INTO FILMES (CODFILME, TITULO, GENERO, ANO_LANCAMENTO, VALOR)
VALUES (4, 'Toy Story', 'Animação', 1995, 24.90);

INSERT INTO FILMES (CODFILME, TITULO, GENERO, ANO_LANCAMENTO, VALOR)
VALUES (5, 'Coringa', 'Drama', 2019, 32.90);

INSERT INTO FILMES (CODFILME, TITULO, GENERO, ANO_LANCAMENTO, VALOR)
VALUES (6, 'Vingadores: Ultimato', 'Ação', 2019, 44.90);

INSERT INTO LOCACOES (CODLOCACAO, CODCLIENTE, CODFILME, DATA_LOCACAO, VALOR_PAGO)
VALUES (1, 1, 3, DATE '2026-04-10', 34.90);

INSERT INTO LOCACOES (CODLOCACAO, CODCLIENTE, CODFILME, DATA_LOCACAO, VALOR_PAGO)
VALUES (2, 2, 1, DATE '2026-04-11', 29.90);

INSERT INTO LOCACOES (CODLOCACAO, CODCLIENTE, CODFILME, DATA_LOCACAO, VALOR_PAGO)
VALUES (3, 3, 6, DATE '2026-04-12', 44.90);

INSERT INTO LOCACOES (CODLOCACAO, CODCLIENTE, CODFILME, DATA_LOCACAO, VALOR_PAGO)
VALUES (4, 1, 2, DATE '2026-04-15', 39.90);

INSERT INTO LOCACOES (CODLOCACAO, CODCLIENTE, CODFILME, DATA_LOCACAO, VALOR_PAGO)
VALUES (5, 4, 4, DATE '2026-04-16', 24.90);

INSERT INTO LOCACOES (CODLOCACAO, CODCLIENTE, CODFILME, DATA_LOCACAO, VALOR_PAGO)
VALUES (6, 5, 1, DATE '2026-04-18', 29.90);

INSERT INTO LOCACOES (CODLOCACAO, CODCLIENTE, CODFILME, DATA_LOCACAO, VALOR_PAGO)
VALUES (7, 2, 5, DATE '2026-04-20', 32.90);

INSERT INTO LOCACOES (CODLOCACAO, CODCLIENTE, CODFILME, DATA_LOCACAO, VALOR_PAGO)
VALUES (8, 3, 3, DATE '2026-04-22', 34.90);

COMMIT;
