-- ==========================================
-- ANÁLISES DE NEGÓCIO
-- ==========================================


-- 1. Quantidade de locações por cliente
SELECT
    cl.NOME AS CLIENTE,
    COUNT(l.CODLOCACAO) AS QUANTIDADE_LOCACOES
FROM CLIENTES cl
INNER JOIN LOCACOES l
    ON cl.CODCLIENTE = l.CODCLIENTE
GROUP BY cl.NOME
ORDER BY QUANTIDADE_LOCACOES DESC;


-- 2. Total gasto por cliente
SELECT
    cl.NOME AS CLIENTE,
    SUM(l.VALOR_PAGO) AS TOTAL_GASTO
FROM CLIENTES cl
INNER JOIN LOCACOES l
    ON cl.CODCLIENTE = l.CODCLIENTE
GROUP BY cl.NOME
ORDER BY TOTAL_GASTO DESC;


-- 3. Quantidade de locações por filme
SELECT
    f.TITULO AS FILME,
    COUNT(l.CODLOCACAO) AS QUANTIDADE_LOCACOES
FROM FILMES f
INNER JOIN LOCACOES l
    ON f.CODFILME = l.CODFILME
GROUP BY f.TITULO
ORDER BY QUANTIDADE_LOCACOES DESC;


-- 4. Faturamento por filme
SELECT
    f.TITULO AS FILME,
    SUM(l.VALOR_PAGO) AS FATURAMENTO
FROM FILMES f
INNER JOIN LOCACOES l
    ON f.CODFILME = l.CODFILME
GROUP BY f.TITULO
ORDER BY FATURAMENTO DESC;


-- 5. Faturamento total das locações
SELECT
    SUM(VALOR_PAGO) AS FATURAMENTO_TOTAL
FROM LOCACOES;


-- 6. Valor médio das locações
SELECT
    AVG(VALOR_PAGO) AS VALOR_MEDIO_LOCACAO
FROM LOCACOES;


-- 7. Cliente que realizou mais locações
SELECT
    cl.NOME AS CLIENTE,
    COUNT(l.CODLOCACAO) AS QUANTIDADE_LOCACOES
FROM CLIENTES cl
INNER JOIN LOCACOES l
    ON cl.CODCLIENTE = l.CODCLIENTE
GROUP BY cl.NOME
ORDER BY QUANTIDADE_LOCACOES DESC
FETCH FIRST 1 ROW ONLY;


-- 8. Cliente que mais gastou
SELECT
    cl.NOME AS CLIENTE,
    SUM(l.VALOR_PAGO) AS TOTAL_GASTO
FROM CLIENTES cl
INNER JOIN LOCACOES l
    ON cl.CODCLIENTE = l.CODCLIENTE
GROUP BY cl.NOME
ORDER BY TOTAL_GASTO DESC
FETCH FIRST 1 ROW ONLY;


-- 9. Filme mais alugado
SELECT
    f.TITULO AS FILME,
    COUNT(l.CODLOCACAO) AS QUANTIDADE_LOCACOES
FROM FILMES f
INNER JOIN LOCACOES l
    ON f.CODFILME = l.CODFILME
GROUP BY f.TITULO
ORDER BY QUANTIDADE_LOCACOES DESC
FETCH FIRST 1 ROW ONLY;


-- 10. Locações acima da média
SELECT
    l.CODLOCACAO,
    cl.NOME AS CLIENTE,
    f.TITULO AS FILME,
    l.VALOR_PAGO
FROM LOCACOES l
INNER JOIN CLIENTES cl
    ON l.CODCLIENTE = cl.CODCLIENTE
INNER JOIN FILMES f
    ON l.CODFILME = f.CODFILME
WHERE l.VALOR_PAGO > (
    SELECT AVG(VALOR_PAGO)
    FROM LOCACOES
)
ORDER BY l.VALOR_PAGO DESC;
